import { createApp } from "vue";
import "./style.scss";
import App from "./App.vue";
import router from "./router";
import util from "./plugin/util";
import store from "./store";
import axios from "axios";
import SvgIcon from "vue3-icon";
import BaseCheckBox from "@/components/common/BaseCheckBox.vue";
import BaseSelectBox from "@/components/common/BaseSelectBox.vue";
import BaseModal from "@/components/common/BaseModal.vue";
import SlideUpDown from "vue3-slide-up-down";
const app = createApp(App);
console.log(app.config);
app.config.globalProperties.axios = axios;
app.component("svg-icon", SvgIcon);
app.component("CheckBox", BaseCheckBox);
app.component("BaseModal", BaseModal);
app.component("BaseSelectBox", BaseSelectBox);
app.component("slide-up-down", SlideUpDown);
app.use(router).use(store).use(util).mount("#app");
