import { createApp } from "vue";
import "./style.scss";
import App from "./App.vue";
import router from "./router";
import util from "./plugin/util";
import store from "./store";
import axios from "axios";
import SvgIcon from "vue3-icon";
import BaseCheckBox from "@/components/common/BaseCheckBox.vue";
const app = createApp(App);
app.config.globalProperties.axios = axios;
app.component("svg-icon", SvgIcon);
app.component("CheckBox", BaseCheckBox);
app.use(router).use(store).use(util).mount("#app");
